INSERT INTO Words VALUES (1,1,"á","a-accute");
INSERT INTO Words VALUES (1,2,"é","e-accute");
INSERT INTO Words VALUES (1,3,"í","i-accute");
INSERT INTO Words VALUES (1,4,"ó","0-accute");
INSERT INTO Words VALUES (1,5,"ú","u-accute");

INSERT INTO Words VALUES (142,1,"","person/individual/I");
INSERT INTO Words VALUES (142,2,"","Blissymbolics");
INSERT INTO Words VALUES (142,3,"","Speciality/It is");
INSERT INTO Words VALUES (142,4,"","Question/Is");
INSERT INTO Words VALUES (142,5,"","steam/vapour/boiling water");
INSERT INTO Words VALUES (142,6,"","Per centage");
INSERT INTO Words VALUES (142,7,"","Not/opposite");
INSERT INTO Words VALUES (142,8,"","Number");
INSERT INTO Words VALUES (142,9,"","repeating/which");
INSERT INTO Words VALUES (142,10,"",":/that");
INSERT INTO Words VALUES (142,11,"","a/an/any");
INSERT INTO Words VALUES (142,12,"","that/those");
INSERT INTO Words VALUES (142,13,"","the");
INSERT INTO Words VALUES (142,14,"","this/these");
INSERT INTO Words VALUES (142,15,"","but");
INSERT INTO Words VALUES (142,277,"","to happen (for if and for then)");
INSERT INTO Words VALUES (142,16,"","fire");
INSERT INTO Words VALUES (142,17,"","pluralise/personalise/of <something>/<x>'s (possessive noun)");
INSERT INTO Words VALUES (142,18,"","less/not having");
INSERT INTO Words VALUES (142,19,"","multiple of <something>, like group/crowd when with person");
INSERT INTO Words VALUES (142,20,"","male, man, gentleman");
INSERT INTO Words VALUES (142,21,"","measure/measurement/scale");
INSERT INTO Words VALUES (142,22,"","mid .");
INSERT INTO Words VALUES (142,23,"","mid 0");
INSERT INTO Words VALUES (142,24,"","initial/mid 1");
INSERT INTO Words VALUES (142,25,"","mid 2");
INSERT INTO Words VALUES (142,26,"","mid 3");
INSERT INTO Words VALUES (142,27,"","mid 4");
INSERT INTO Words VALUES (142,28,"","mid 5");
INSERT INTO Words VALUES (142,29,"","mid 6");
INSERT INTO Words VALUES (142,30,"","mid 7");
INSERT INTO Words VALUES (142,31,"","mid 8");
INSERT INTO Words VALUES (142,32,"","mid 9");
INSERT INTO Words VALUES (142,33,"","long/range");
INSERT INTO Words VALUES (142,34,"","funnel/filtration");
INSERT INTO Words VALUES (142,35,"","test tube");
INSERT INTO Words VALUES (142,36,"","corpse");
INSERT INTO Words VALUES (142,37,"","passenger");
INSERT INTO Words VALUES (142,38,"","child version");
INSERT INTO Words VALUES (142,39,"","of");
INSERT INTO Words VALUES (142,40,"","for");
INSERT INTO Words VALUES (142,41,"","next to");
INSERT INTO Words VALUES (142,42,"","female/woman/lady");
INSERT INTO Words VALUES (142,43,"","corpse");
INSERT INTO Words VALUES (142,44,"","it");
INSERT INTO Words VALUES (142,45,"","citizen");
INSERT INTO Words VALUES (142,46,"","flag");
INSERT INTO Words VALUES (142,47,"","state/country/territory");
INSERT INTO Words VALUES (142,48,"","territory/state");
INSERT INTO Words VALUES (142,49,"","territories");
INSERT INTO Words VALUES (142,50,"","province/countryside");
INSERT INTO Words VALUES (142,51,"","to lead/to govern/to guide");
INSERT INTO Words VALUES (142,52,"","higher order/Majesty");
INSERT INTO Words VALUES (142,53,"","container");
INSERT INTO Words VALUES (142,54,"","relative position");
INSERT INTO Words VALUES (142,55,"","home country");
INSERT INTO Words VALUES (142,56,"","bounded area");
INSERT INTO Words VALUES (142,57,"","election/vote");
INSERT INTO Words VALUES (142,58,"","(in) action");
INSERT INTO Words VALUES (142,59,"","Britain");
INSERT INTO Words VALUES (142,60,"","United States of America");
INSERT INTO Words VALUES (142,61,"","Australia");
INSERT INTO Words VALUES (142,62,"","New Zealand");
INSERT INTO Words VALUES (142,63,"","father");
INSERT INTO Words VALUES (142,64,"","mother");
INSERT INTO Words VALUES (142,65,"","birth");
INSERT INTO Words VALUES (142,66,"","paper/certificate");
INSERT INTO Words VALUES (142,67,"","married couple");
INSERT INTO Words VALUES (142,68,"","married couple");
INSERT INTO Words VALUES (142,69,"","married couple");
INSERT INTO Words VALUES (142,70,"","parents");
INSERT INTO Words VALUES (142,71,"","parents");
INSERT INTO Words VALUES (142,72,"","parents");
INSERT INTO Words VALUES (142,73,"","husband");
INSERT INTO Words VALUES (142,74,"","wife");
INSERT INTO Words VALUES (142,75,"","before");
INSERT INTO Words VALUES (142,76,"","after");
INSERT INTO Words VALUES (142,77,"","heart/conscience/emotion/passion/imulse/id");
INSERT INTO Words VALUES (142,78,"","love");
INSERT INTO Words VALUES (142,79,"","son");
INSERT INTO Words VALUES (142,80,"","daughter");
INSERT INTO Words VALUES (142,81,"","marriage");
INSERT INTO Words VALUES (142,82,"","roof/cover/care/protection/clad");
INSERT INTO Words VALUES (142,83,"","relative/male relative");
INSERT INTO Words VALUES (142,84,"","relative/female relative");
INSERT INTO Words VALUES (142,85,"","male");
INSERT INTO Words VALUES (142,86,"","female");
INSERT INTO Words VALUES (142,87,"","ring");
INSERT INTO Words VALUES (142,88,"","life/existence/exists/lives");
INSERT INTO Words VALUES (142,89,"","death");
INSERT INTO Words VALUES (142,90,"","water/moisture");
INSERT INTO Words VALUES (142,91,"","thing");
INSERT INTO Words VALUES (142,92,"","to be (in mind)/there is/is");
INSERT INTO Words VALUES (142,93,"","occurrence");
INSERT INTO Words VALUES (142,94,"","part (+)/partition/divorce");
INSERT INTO Words VALUES (142,95,"","sun");
INSERT INTO Words VALUES (142,96,"","morning");
INSERT INTO Words VALUES (142,97,"","day");
INSERT INTO Words VALUES (142,98,"","Monday");
INSERT INTO Words VALUES (142,99,"","Tuesday");
INSERT INTO Words VALUES (142,100,"","Wednesday");
INSERT INTO Words VALUES (142,101,"","Thursday");
INSERT INTO Words VALUES (142,102,"","Friday");
INSERT INTO Words VALUES (142,103,"","Saturday");
INSERT INTO Words VALUES (142,104,"","Sunday");
INSERT INTO Words VALUES (142,105,"","weekday");
INSERT INTO Words VALUES (142,106,"","weekend");
INSERT INTO Words VALUES (142,107,"","before");
INSERT INTO Words VALUES (142,108,"","now");
INSERT INTO Words VALUES (142,109,"","after");
INSERT INTO Words VALUES (142,110,"","generalisation");
INSERT INTO Words VALUES (142,111,"","month");
INSERT INTO Words VALUES (142,112,"","year");
INSERT INTO Words VALUES (142,113,"","light/to shine/illuminate/glows/shines/lamp");
INSERT INTO Words VALUES (142,114,"","electricity/live wire");
INSERT INTO Words VALUES (142,115,"","thing, chemical thing");
INSERT INTO Words VALUES (142,116,"","moon");
INSERT INTO Words VALUES (142,117,"","night");
INSERT INTO Words VALUES (142,118,"","evening");
INSERT INTO Words VALUES (142,119,"","mid slash");
INSERT INTO Words VALUES (142,120,"","star");
INSERT INTO Words VALUES (142,121,"","comet");
INSERT INTO Words VALUES (142,122,"","planet/globe/earth");
INSERT INTO Words VALUES (142,123,"","earth's crust");
INSERT INTO Words VALUES (142,124,"","centre of the earth");
INSERT INTO Words VALUES (142,125,"","centre of the earth");
INSERT INTO Words VALUES (142,126,"","north pole");
INSERT INTO Words VALUES (142,127,"","south pole");
INSERT INTO Words VALUES (142,128,"","northern hemisphere");
INSERT INTO Words VALUES (142,129,"","southern hemisphere");
INSERT INTO Words VALUES (142,130,"","north");
INSERT INTO Words VALUES (142,131,"","south");
INSERT INTO Words VALUES (142,132,"","east");
INSERT INTO Words VALUES (142,133,"","west");
INSERT INTO Words VALUES (142,134,"","compass");
INSERT INTO Words VALUES (142,135,"","turn/rotate/gyrate");
INSERT INTO Words VALUES (142,136,"","wheel/mechanism");
INSERT INTO Words VALUES (142,137,"","travel/journey");
INSERT INTO Words VALUES (142,138,"","man made/make/prepare/produce");
INSERT INTO Words VALUES (142,139,"","place/address");
INSERT INTO Words VALUES (142,140,"","house/building");
INSERT INTO Words VALUES (142,141,"","floor");
INSERT INTO Words VALUES (142,142,"","chimney");
INSERT INTO Words VALUES (142,143,"","backyard");
INSERT INTO Words VALUES (142,144,"","future");
INSERT INTO Words VALUES (142,145,"","walls");
INSERT INTO Words VALUES (142,146,"","timed thing/with timing/repeats");
INSERT INTO Words VALUES (142,147,"","eye/seeing");
INSERT INTO Words VALUES (142,148,"","music/musical note");
INSERT INTO Words VALUES (142,149,"","mouth");
INSERT INTO Words VALUES (142,150,"","legs and feet");
INSERT INTO Words VALUES (142,151,"","ear");
INSERT INTO Words VALUES (142,152,"","addition");
INSERT INTO Words VALUES (142,153,"","possession");
INSERT INTO Words VALUES (142,154,"","has/have");
INSERT INTO Words VALUES (142,155,"","had");
INSERT INTO Words VALUES (142,156,"","subtraction/waste");
INSERT INTO Words VALUES (142,157,"","multiplication");
INSERT INTO Words VALUES (142,158,"","part/division");
INSERT INTO Words VALUES (142,159,"","more than/in relation to/greater than");
INSERT INTO Words VALUES (142,160,"","to relate");
INSERT INTO Words VALUES (142,161,"","point of view (conscience)");
INSERT INTO Words VALUES (142,162,"","first alternative");
INSERT INTO Words VALUES (142,163,"","cause");
INSERT INTO Words VALUES (142,164,"","effect");
INSERT INTO Words VALUES (142,165,"","cause and effect/causation");
INSERT INTO Words VALUES (142,166,"","cause");
INSERT INTO Words VALUES (142,167,"","effect");
INSERT INTO Words VALUES (142,168,"","less than/in relation to");
INSERT INTO Words VALUES (142,169,"","second alternative");
INSERT INTO Words VALUES (142,170,"","either");
INSERT INTO Words VALUES (142,171,"","therefore/consequently/by/causes");
INSERT INTO Words VALUES (142,172,"","or");
INSERT INTO Words VALUES (142,173,"","by/caused by");
INSERT INTO Words VALUES (142,174,"","and/to/also/positive/plus/with/too/further/besides/et");
INSERT INTO Words VALUES (142,175,"","with (help with)");
INSERT INTO Words VALUES (142,176,"","without");
INSERT INTO Words VALUES (142,177,"","more");
INSERT INTO Words VALUES (142,178,"","prefer");
INSERT INTO Words VALUES (142,179,"","most/best/formal");
INSERT INTO Words VALUES (142,180,"","all (within limits)");
INSERT INTO Words VALUES (142,181,"","all (everything)");
INSERT INTO Words VALUES (142,182,"1","first");
INSERT INTO Words VALUES (142,183,"","nd/rd/th");
INSERT INTO Words VALUES (142,184,"","forward/to/progress/go/on/advance/dynamic/direction/way/path");
INSERT INTO Words VALUES (142,185,"","backward/return/reverse/retreat");
INSERT INTO Words VALUES (142,186,"","to and fro/vice-versa");
INSERT INTO Words VALUES (142,187,"","conformity/concord/harmony/agreement");
INSERT INTO Words VALUES (142,188,"","competition/race/versus");
INSERT INTO Words VALUES (142,189,"","obstacle/opposition/difficulty/trouble/counter force/complexity (?)");
INSERT INTO Words VALUES (142,190,"","in spite of/spite");
INSERT INTO Words VALUES (142,191,"","in spite of/though/although/notwithstanding/nevertheless");
INSERT INTO Words VALUES (142,192,"","success");
INSERT INTO Words VALUES (142,193,"","up (arrow)/goes up/lift/take off/rise/shift (?)");
INSERT INTO Words VALUES (142,194,"","down (arrow)/goes down/drop/fall");
INSERT INTO Words VALUES (142,195,"","collection/meeting");
INSERT INTO Words VALUES (142,196,"","gathering");
INSERT INTO Words VALUES (142,197,"","meeting");
INSERT INTO Words VALUES (142,198,"","separation");
INSERT INTO Words VALUES (142,199,"","expansion");
INSERT INTO Words VALUES (142,200,"","distribution");
INSERT INTO Words VALUES (142,201,"","moving up");
INSERT INTO Words VALUES (142,202,"","moving up");
INSERT INTO Words VALUES (142,203,"","moving down");
INSERT INTO Words VALUES (142,204,"","moving down");
INSERT INTO Words VALUES (142,205,"","start/begin/depart");
INSERT INTO Words VALUES (142,206,"","position/point in space/point in time");
INSERT INTO Words VALUES (142,207,"","arrival/stop/end/to/off/halt");
INSERT INTO Words VALUES (142,208,"","bombards/bombarding");
INSERT INTO Words VALUES (142,209,"","to pass by");
INSERT INTO Words VALUES (142,210,"","to continue");
INSERT INTO Words VALUES (142,211,"","through/pass through/non-stop/break through");
INSERT INTO Words VALUES (142,212,"","splits into/which disintegrates into/turns into");
INSERT INTO Words VALUES (142,213,"","that");
INSERT INTO Words VALUES (142,214,"","that (he said:)");
INSERT INTO Words VALUES (142,215,"","to/till/to the");
INSERT INTO Words VALUES (142,216,"","small position/small start point");
INSERT INTO Words VALUES (142,217,"","medicine/medical");
INSERT INTO Words VALUES (142,218,"","stethoscope (abbreviated)");
INSERT INTO Words VALUES (142,219,"","syringe");
INSERT INTO Words VALUES (142,220,"","into/enter/insert");
INSERT INTO Words VALUES (142,221,"","money/cash/price");
INSERT INTO Words VALUES (142,222,"","business/trade");
INSERT INTO Words VALUES (142,223,"","safe");
INSERT INTO Words VALUES (142,224,"","bank");
INSERT INTO Words VALUES (142,225,"","notes/paper money");
INSERT INTO Words VALUES (142,226,"","account");
INSERT INTO Words VALUES (142,227,"","safe custody");
INSERT INTO Words VALUES (142,228,"","bankrupt, bankruptcy");
INSERT INTO Words VALUES (142,229,"","disc/pill");
INSERT INTO Words VALUES (142,230,"","to cross out/to blot out/destroy");
INSERT INTO Words VALUES (142,231,"","a ruin");
INSERT INTO Words VALUES (142,232,"","equal/equals/are/same");
INSERT INTO Words VALUES (142,233,"","not equal/different");
INSERT INTO Words VALUES (142,234,"","is proportional to (?)");
INSERT INTO Words VALUES (142,235,"","solid/solid thing");
INSERT INTO Words VALUES (142,236,"","liquid");
INSERT INTO Words VALUES (142,237,"","melting");
INSERT INTO Words VALUES (142,238,"","metal");
INSERT INTO Words VALUES (142,239,"","raw material/material");
INSERT INTO Words VALUES (142,240,"","crystal");
INSERT INTO Words VALUES (142,241,"","classify/classification");
INSERT INTO Words VALUES (142,242,"","crystal axis");
INSERT INTO Words VALUES (142,243,"","change");
INSERT INTO Words VALUES (142,244,"","thing on earth");
INSERT INTO Words VALUES (142,245,"","soap");
INSERT INTO Words VALUES (142,246,"","above/over");
INSERT INTO Words VALUES (142,247,"","below/under");
INSERT INTO Words VALUES (142,248,"","conjunction/junction/joint/union/combination/coalition/alliance/connection/link/couple");
INSERT INTO Words VALUES (142,249,"","tool");
INSERT INTO Words VALUES (142,250,"","connection/junction (basic)");
INSERT INTO Words VALUES (142,251,"","chains");
INSERT INTO Words VALUES (142,252,"","chain link");
INSERT INTO Words VALUES (142,253,"","gas");
INSERT INTO Words VALUES (142,254,"","gas-filled");
INSERT INTO Words VALUES (142,255,"","thermometer");
INSERT INTO Words VALUES (142,256,"","tripod");
INSERT INTO Words VALUES (142,257,"","glass flask/Erlenmeyer");
INSERT INTO Words VALUES (142,258,"","cock/tap");
INSERT INTO Words VALUES (142,259,"","burette");
INSERT INTO Words VALUES (142,260,"","manometer/air pressure");
INSERT INTO Words VALUES (142,261,"","filter process");
INSERT INTO Words VALUES (142,262,"","filtration (laboratory)");
INSERT INTO Words VALUES (142,263,"","calibrated cylinder/measuring glass");
INSERT INTO Words VALUES (142,264,"","solution");
INSERT INTO Words VALUES (142,265,"","solution");
INSERT INTO Words VALUES (142,266,"","The upper part");
INSERT INTO Words VALUES (142,267,"","The middle part");
INSERT INTO Words VALUES (142,268,"","evaluation/the value/human evaluation");
INSERT INTO Words VALUES (142,269,"","to evaluate");
INSERT INTO Words VALUES (142,270,"","precipitation");
INSERT INTO Words VALUES (142,271,"","solution plus sediment");
INSERT INTO Words VALUES (142,272,"","solution plus crystal sediment");
INSERT INTO Words VALUES (142,273,"","diaphragm");
INSERT INTO Words VALUES (142,274,"","filtration (in industry)");
INSERT INTO Words VALUES (142,275,"","osmosis");
INSERT INTO Words VALUES (142,276,"","dialysis (colloid-solution)");
-- --INSERT INTO Words VALUES (142,277,"","");
--INSERT INTO Words VALUES (142,278,"","");
--INSERT INTO Words VALUES (142,279,"","");
--INSERT INTO Words VALUES (142,280,"","");
--INSERT INTO Words VALUES (142,281,"","");
--INSERT INTO Words VALUES (142,282,"","");
--INSERT INTO Words VALUES (142,283,"","");
--INSERT INTO Words VALUES (142,284,"","");
--INSERT INTO Words VALUES (142,285,"","");
--INSERT INTO Words VALUES (142,286,"","");
--INSERT INTO Words VALUES (142,287,"","");
--INSERT INTO Words VALUES (142,288,"","");
--INSERT INTO Words VALUES (142,289,"","");
--INSERT INTO Words VALUES (142,290,"","");
--INSERT INTO Words VALUES (142,291,"","");
--INSERT INTO Words VALUES (142,292,"","");
--INSERT INTO Words VALUES (142,293,"","");
--INSERT INTO Words VALUES (142,294,"","");
--INSERT INTO Words VALUES (142,295,"","");
--INSERT INTO Words VALUES (142,296,"","");
--INSERT INTO Words VALUES (142,297,"","");
--INSERT INTO Words VALUES (142,298,"","");
--INSERT INTO Words VALUES (142,299,"","");
--INSERT INTO Words VALUES (142,300,"","");
--INSERT INTO Words VALUES (142,301,"","");
--INSERT INTO Words VALUES (142,302,"","");
--INSERT INTO Words VALUES (142,303,"","");
--INSERT INTO Words VALUES (142,304,"","");
--INSERT INTO Words VALUES (142,305,"","");
--INSERT INTO Words VALUES (142,306,"","");
--INSERT INTO Words VALUES (142,307,"","");
--INSERT INTO Words VALUES (142,308,"","");
--INSERT INTO Words VALUES (142,309,"","");
--INSERT INTO Words VALUES (142,310,"","");
--INSERT INTO Words VALUES (142,311,"","");
--INSERT INTO Words VALUES (142,312,"","");
--INSERT INTO Words VALUES (142,313,"","");
--INSERT INTO Words VALUES (142,314,"","");
--INSERT INTO Words VALUES (142,315,"","");
--INSERT INTO Words VALUES (142,316,"","");
--INSERT INTO Words VALUES (142,317,"","");
--INSERT INTO Words VALUES (142,318,"","");
--INSERT INTO Words VALUES (142,319,"","");
--INSERT INTO Words VALUES (142,320,"","");
--INSERT INTO Words VALUES (142,321,"","");
--INSERT INTO Words VALUES (142,322,"","");
--INSERT INTO Words VALUES (142,323,"","");
--INSERT INTO Words VALUES (142,324,"","");
--INSERT INTO Words VALUES (142,325,"","");
--INSERT INTO Words VALUES (142,326,"","");
--INSERT INTO Words VALUES (142,327,"","");
--INSERT INTO Words VALUES (142,328,"","");
--INSERT INTO Words VALUES (142,329,"","");
--INSERT INTO Words VALUES (142,330,"","");
--INSERT INTO Words VALUES (142,331,"","");
--INSERT INTO Words VALUES (142,332,"","");
--INSERT INTO Words VALUES (142,333,"","");
--INSERT INTO Words VALUES (142,334,"","");
--INSERT INTO Words VALUES (142,335,"","");
--INSERT INTO Words VALUES (142,336,"","");
--INSERT INTO Words VALUES (142,337,"","");
--INSERT INTO Words VALUES (142,338,"","");
--INSERT INTO Words VALUES (142,339,"","");
--INSERT INTO Words VALUES (142,340,"","");
--INSERT INTO Words VALUES (142,341,"","");
--INSERT INTO Words VALUES (142,342,"","");
--INSERT INTO Words VALUES (142,343,"","");
--INSERT INTO Words VALUES (142,344,"","");
--INSERT INTO Words VALUES (142,345,"","");
--INSERT INTO Words VALUES (142,346,"","");
--INSERT INTO Words VALUES (142,347,"","");
--INSERT INTO Words VALUES (142,348,"","");
--INSERT INTO Words VALUES (142,349,"","");
--INSERT INTO Words VALUES (142,350,"","");
--INSERT INTO Words VALUES (142,351,"","");
--INSERT INTO Words VALUES (142,352,"","");
--INSERT INTO Words VALUES (142,353,"","");
--INSERT INTO Words VALUES (142,354,"","");
--INSERT INTO Words VALUES (142,355,"","");
--INSERT INTO Words VALUES (142,356,"","");
--INSERT INTO Words VALUES (142,357,"","");
--INSERT INTO Words VALUES (142,358,"","");
--INSERT INTO Words VALUES (142,359,"","");
--INSERT INTO Words VALUES (142,360,"","");
--INSERT INTO Words VALUES (142,361,"","");
--INSERT INTO Words VALUES (142,362,"","");
--INSERT INTO Words VALUES (142,363,"","");
--INSERT INTO Words VALUES (142,364,"","");
--INSERT INTO Words VALUES (142,365,"","");
--INSERT INTO Words VALUES (142,366,"","");
--INSERT INTO Words VALUES (142,367,"","");
--INSERT INTO Words VALUES (142,368,"","");
--INSERT INTO Words VALUES (142,369,"","");
--INSERT INTO Words VALUES (142,370,"","");
--INSERT INTO Words VALUES (142,371,"","");
--INSERT INTO Words VALUES (142,372,"","");
--INSERT INTO Words VALUES (142,373,"","");
--INSERT INTO Words VALUES (142,374,"","");
--INSERT INTO Words VALUES (142,375,"","");
--INSERT INTO Words VALUES (142,376,"","");
--INSERT INTO Words VALUES (142,377,"","");
--INSERT INTO Words VALUES (142,378,"","");
--INSERT INTO Words VALUES (142,379,"","");
--INSERT INTO Words VALUES (142,380,"","");
--INSERT INTO Words VALUES (142,381,"","");
--INSERT INTO Words VALUES (142,382,"","");
--INSERT INTO Words VALUES (142,383,"","");
--INSERT INTO Words VALUES (142,384,"","");
--INSERT INTO Words VALUES (142,385,"","");
--INSERT INTO Words VALUES (142,386,"","");
--INSERT INTO Words VALUES (142,387,"","");
--INSERT INTO Words VALUES (142,388,"","");
--INSERT INTO Words VALUES (142,389,"","");
--INSERT INTO Words VALUES (142,390,"","");
--INSERT INTO Words VALUES (142,391,"","");
--INSERT INTO Words VALUES (142,392,"","");
--INSERT INTO Words VALUES (142,393,"","");
--INSERT INTO Words VALUES (142,394,"","");
--INSERT INTO Words VALUES (142,395,"","");
--INSERT INTO Words VALUES (142,396,"","");
--INSERT INTO Words VALUES (142,397,"","");
--INSERT INTO Words VALUES (142,398,"","");
--INSERT INTO Words VALUES (142,399,"","");
