INSERT INTO Words VALUES (1,1,"á","a-accute");
INSERT INTO Words VALUES (1,2,"é","e-accute");
INSERT INTO Words VALUES (1,3,"í","i-accute");
INSERT INTO Words VALUES (1,4,"ó","0-accute");
INSERT INTO Words VALUES (1,5,"ú","u-accute");

INSERT INTO Words VALUES (142,1,"","person/individual/I");
INSERT INTO Words VALUES (142,2,"","Blissymbolics");
INSERT INTO Words VALUES (142,3,"","Speciality/It is");
INSERT INTO Words VALUES (142,4,"","Question/Is");
INSERT INTO Words VALUES (142,5,"","steam/vapour/boiling water");
INSERT INTO Words VALUES (142,6,"","Per cent");
INSERT INTO Words VALUES (142,7,"","Not/opposite");
INSERT INTO Words VALUES (142,8,"","Number");
INSERT INTO Words VALUES (142,9,"","repeating/which");
INSERT INTO Words VALUES (142,10,"",":/that");
INSERT INTO Words VALUES (142,11,"","a/an/any");
INSERT INTO Words VALUES (142,12,"","that/those");
INSERT INTO Words VALUES (142,13,"","the");
INSERT INTO Words VALUES (142,14,"","this/these");
INSERT INTO Words VALUES (142,15,"","but");
INSERT INTO Words VALUES (142,16,"","fire");
INSERT INTO Words VALUES (142,17,"","pluralise/personalise/of <something>/<x>'s (possessive noun)");
INSERT INTO Words VALUES (142,18,"","less/not having");
INSERT INTO Words VALUES (142,19,"","multiple of <something>, like group/crowd when with person");
INSERT INTO Words VALUES (142,20,"","male, man, gentleman");
INSERT INTO Words VALUES (142,21,"","measure/measurement/scale");
INSERT INTO Words VALUES (142,22,"","mid .");
INSERT INTO Words VALUES (142,23,"","mid 0");
INSERT INTO Words VALUES (142,24,"","initial/mid 1");
INSERT INTO Words VALUES (142,25,"","mid 2");
INSERT INTO Words VALUES (142,26,"","mid 3");
INSERT INTO Words VALUES (142,27,"","mid 4");
INSERT INTO Words VALUES (142,28,"","mid 5");
INSERT INTO Words VALUES (142,29,"","mid 6");
INSERT INTO Words VALUES (142,30,"","mid 7");
INSERT INTO Words VALUES (142,31,"","mid 8");
INSERT INTO Words VALUES (142,32,"","mid 9");
INSERT INTO Words VALUES (142,33,"","long/range");
INSERT INTO Words VALUES (142,34,"","funnel/filtration");
INSERT INTO Words VALUES (142,35,"","test tube");
INSERT INTO Words VALUES (142,36,"","corpse");
INSERT INTO Words VALUES (142,37,"","passenger");
INSERT INTO Words VALUES (142,38,"","young/new/child/child version");
INSERT INTO Words VALUES (142,39,"","of");
INSERT INTO Words VALUES (142,40,"","for");
INSERT INTO Words VALUES (142,41,"","next to/near/about");
INSERT INTO Words VALUES (142,42,"","female/woman/lady");
INSERT INTO Words VALUES (142,43,"","corpse");
INSERT INTO Words VALUES (142,44,"","it");
INSERT INTO Words VALUES (142,45,"","citizen");
INSERT INTO Words VALUES (142,46,"","flag");
INSERT INTO Words VALUES (142,47,"","state/country/territory");
INSERT INTO Words VALUES (142,48,"","ground/earth");
INSERT INTO Words VALUES (142,49,"","sky");
INSERT INTO Words VALUES (142,50,"","province/countryside");
INSERT INTO Words VALUES (142,51,"","to lead/to govern/to guide");
INSERT INTO Words VALUES (142,52,"","high/tall/height");
INSERT INTO Words VALUES (142,53,"","container");
INSERT INTO Words VALUES (142,54,"","relative position");
INSERT INTO Words VALUES (142,55,"","home country");
INSERT INTO Words VALUES (142,56,"","bounded area");
INSERT INTO Words VALUES (142,57,"","election/vote");
INSERT INTO Words VALUES (142,58,"","(in) action");
INSERT INTO Words VALUES (142,59,"","Great Britain/The United Kingdom/British");
INSERT INTO Words VALUES (142,60,"","United States of America");
INSERT INTO Words VALUES (142,61,"","Australia");
INSERT INTO Words VALUES (142,62,"","New Zealand");
INSERT INTO Words VALUES (142,63,"","father");
INSERT INTO Words VALUES (142,64,"","mother");
INSERT INTO Words VALUES (142,65,"","birth");
INSERT INTO Words VALUES (142,66,"","paper/certificate");
INSERT INTO Words VALUES (142,67,"","married couple");
INSERT INTO Words VALUES (142,68,"","married couple");
INSERT INTO Words VALUES (142,69,"","married couple");
INSERT INTO Words VALUES (142,70,"","parents");
INSERT INTO Words VALUES (142,71,"","parents");
INSERT INTO Words VALUES (142,72,"","parents");
INSERT INTO Words VALUES (142,73,"","husband");
INSERT INTO Words VALUES (142,74,"","wife");
INSERT INTO Words VALUES (142,75,"","before");
INSERT INTO Words VALUES (142,76,"","after");
INSERT INTO Words VALUES (142,77,"","heart/conscience/emotion/passion/imulse/id");
INSERT INTO Words VALUES (142,78,"","love");
INSERT INTO Words VALUES (142,79,"","son");
INSERT INTO Words VALUES (142,80,"","daughter");
INSERT INTO Words VALUES (142,81,"","marriage");
INSERT INTO Words VALUES (142,82,"","roof/cover/care/protection/clad");
INSERT INTO Words VALUES (142,83,"","relative/male relative");
INSERT INTO Words VALUES (142,84,"","relative/female relative");
INSERT INTO Words VALUES (142,85,"","male/to act");
INSERT INTO Words VALUES (142,86,"","female");
INSERT INTO Words VALUES (142,87,"","ring");
INSERT INTO Words VALUES (142,88,"","life/existence/exists/lives");
INSERT INTO Words VALUES (142,89,"","death");
INSERT INTO Words VALUES (142,90,"","water/moisture");
INSERT INTO Words VALUES (142,91,"","thing");
INSERT INTO Words VALUES (142,92,"","to be (in mind)/there is/is");
INSERT INTO Words VALUES (142,93,"","occurrence");
INSERT INTO Words VALUES (142,94,"","part (+)/partition/divorce");
INSERT INTO Words VALUES (142,95,"","sun/circle");
INSERT INTO Words VALUES (142,96,"","morning");
INSERT INTO Words VALUES (142,97,"","day");
INSERT INTO Words VALUES (142,98,"","Monday");
INSERT INTO Words VALUES (142,99,"","Tuesday");
INSERT INTO Words VALUES (142,100,"","Wednesday");
INSERT INTO Words VALUES (142,101,"","Thursday");
INSERT INTO Words VALUES (142,102,"","Friday");
INSERT INTO Words VALUES (142,103,"","Saturday");
INSERT INTO Words VALUES (142,104,"","Sunday");
INSERT INTO Words VALUES (142,105,"","weekday");
INSERT INTO Words VALUES (142,106,"","weekend");
INSERT INTO Words VALUES (142,107,"","before/then/ago/when");
INSERT INTO Words VALUES (142,108,"","now/just");
INSERT INTO Words VALUES (142,109,"","after/then/hence/when");
INSERT INTO Words VALUES (142,110,"","generalisation/similar to");
INSERT INTO Words VALUES (142,111,"","month");
INSERT INTO Words VALUES (142,112,"","year");
INSERT INTO Words VALUES (142,113,"","light/to shine/illuminate/glows/shines/lamp");
INSERT INTO Words VALUES (142,114,"","electricity/live wire");
INSERT INTO Words VALUES (142,115,"","thing, chemical thing");
INSERT INTO Words VALUES (142,116,"","moon");
INSERT INTO Words VALUES (142,117,"","night");
INSERT INTO Words VALUES (142,118,"","evening");
INSERT INTO Words VALUES (142,119,"","mid slash");
INSERT INTO Words VALUES (142,120,"","star");
INSERT INTO Words VALUES (142,121,"","comet");
INSERT INTO Words VALUES (142,122,"","planet/globe/earth");
INSERT INTO Words VALUES (142,123,"","earth's crust");
INSERT INTO Words VALUES (142,124,"","centre of the earth");
INSERT INTO Words VALUES (142,125,"","centre of the earth");
INSERT INTO Words VALUES (142,126,"","north pole");
INSERT INTO Words VALUES (142,127,"","south pole");
INSERT INTO Words VALUES (142,128,"","northern hemisphere");
INSERT INTO Words VALUES (142,129,"","southern hemisphere");
INSERT INTO Words VALUES (142,130,"","north");
INSERT INTO Words VALUES (142,131,"","south");
INSERT INTO Words VALUES (142,132,"","east");
INSERT INTO Words VALUES (142,133,"","west");
INSERT INTO Words VALUES (142,134,"","compass");
INSERT INTO Words VALUES (142,135,"","turn/rotate/gyrate");
INSERT INTO Words VALUES (142,136,"","wheel/mechanism");
INSERT INTO Words VALUES (142,137,"","travel/journey");
INSERT INTO Words VALUES (142,138,"","man made/make/prepare/produce");
INSERT INTO Words VALUES (142,139,"","place/address");
INSERT INTO Words VALUES (142,140,"","house/building");
INSERT INTO Words VALUES (142,141,"","floor");
INSERT INTO Words VALUES (142,142,"","chimney");
INSERT INTO Words VALUES (142,143,"","backyard");
INSERT INTO Words VALUES (142,144,"","future");
INSERT INTO Words VALUES (142,145,"","walls");
INSERT INTO Words VALUES (142,146,"","timed thing/with timing/repeats");
INSERT INTO Words VALUES (142,147,"","eye/seeing");
INSERT INTO Words VALUES (142,148,"","music/musical note");
INSERT INTO Words VALUES (142,149,"","mouth");
INSERT INTO Words VALUES (142,150,"","legs and feet");
INSERT INTO Words VALUES (142,151,"","ear");
INSERT INTO Words VALUES (142,152,"","addition");
INSERT INTO Words VALUES (142,153,"","possession");
INSERT INTO Words VALUES (142,154,"","has/have");
INSERT INTO Words VALUES (142,155,"","had");
INSERT INTO Words VALUES (142,156,"","subtraction/waste");
INSERT INTO Words VALUES (142,157,"","multiplication");
INSERT INTO Words VALUES (142,158,"","part/division");
INSERT INTO Words VALUES (142,159,"","more than/in relation to/greater than");
INSERT INTO Words VALUES (142,160,"","to relate");
INSERT INTO Words VALUES (142,161,"","point of view (conscience)");
INSERT INTO Words VALUES (142,162,"","first alternative");
INSERT INTO Words VALUES (142,163,"","cause");
INSERT INTO Words VALUES (142,164,"","effect");
INSERT INTO Words VALUES (142,165,"","cause and effect/causation");
INSERT INTO Words VALUES (142,166,"","cause");
INSERT INTO Words VALUES (142,167,"","effect");
INSERT INTO Words VALUES (142,168,"","less than/in relation to");
INSERT INTO Words VALUES (142,169,"","second alternative");
INSERT INTO Words VALUES (142,170,"","either/to happen (for if and for then)");
INSERT INTO Words VALUES (142,171,"","therefore/consequently/by/causes");
INSERT INTO Words VALUES (142,172,"","or");
INSERT INTO Words VALUES (142,173,"","by/caused by");
INSERT INTO Words VALUES (142,174,"","and/to/also/positive/plus/with/too/further/besides/et");
INSERT INTO Words VALUES (142,175,"","with (help with)");
INSERT INTO Words VALUES (142,176,"","without");
INSERT INTO Words VALUES (142,177,"","more");
INSERT INTO Words VALUES (142,178,"","prefer");
INSERT INTO Words VALUES (142,179,"","most/best/formal");
INSERT INTO Words VALUES (142,180,"","all (within limits)");
INSERT INTO Words VALUES (142,181,"","all (everything)");
INSERT INTO Words VALUES (142,182,"1","first");
INSERT INTO Words VALUES (142,183,"","nd/rd/th");
INSERT INTO Words VALUES (142,184,"","forward/to/progress/go/on/advance/dynamic/direction/way/path");
INSERT INTO Words VALUES (142,185,"","backward/return/reverse/retreat");
INSERT INTO Words VALUES (142,186,"","to and fro/vice-versa");
INSERT INTO Words VALUES (142,187,"","conformity/concord/harmony/agreement");
INSERT INTO Words VALUES (142,188,"","competition/race/versus");
INSERT INTO Words VALUES (142,189,"","obstacle/opposition/difficulty/trouble/counter force/complexity (?)");
INSERT INTO Words VALUES (142,190,"","in spite of/spite");
INSERT INTO Words VALUES (142,191,"","in spite of/though/although/notwithstanding/nevertheless");
INSERT INTO Words VALUES (142,192,"","success");
INSERT INTO Words VALUES (142,193,"","up (arrow)/goes up/lift/take off/rise/shift (?)");
INSERT INTO Words VALUES (142,194,"","down (arrow)/goes down/drop/fall");
INSERT INTO Words VALUES (142,195,"","collection/meeting");
INSERT INTO Words VALUES (142,196,"","gathering");
INSERT INTO Words VALUES (142,197,"","meeting");
INSERT INTO Words VALUES (142,198,"","separation");
INSERT INTO Words VALUES (142,199,"","expansion");
INSERT INTO Words VALUES (142,200,"","distribution");
INSERT INTO Words VALUES (142,201,"","moving up");
INSERT INTO Words VALUES (142,202,"","moving up");
INSERT INTO Words VALUES (142,203,"","moving down");
INSERT INTO Words VALUES (142,204,"","moving down");
INSERT INTO Words VALUES (142,205,"","start/begin/depart");
INSERT INTO Words VALUES (142,206,"","line/wire/position/point in space/point in time");
INSERT INTO Words VALUES (142,207,"","arrival/stop/end/to/off/halt");
INSERT INTO Words VALUES (142,208,"","bombards/bombarding");
INSERT INTO Words VALUES (142,209,"","to pass by");
INSERT INTO Words VALUES (142,210,"","to continue");
INSERT INTO Words VALUES (142,211,"","through/pass through/non-stop/break through");
INSERT INTO Words VALUES (142,212,"","splits into/which disintegrates into/turns into");
INSERT INTO Words VALUES (142,213,"","that");
INSERT INTO Words VALUES (142,214,"","that (he said:)");
INSERT INTO Words VALUES (142,215,"","to/till/to the");
INSERT INTO Words VALUES (142,216,"","small position/small start point");
INSERT INTO Words VALUES (142,217,"","medicine/medical");
INSERT INTO Words VALUES (142,218,"","stethoscope (abbreviated)");
INSERT INTO Words VALUES (142,219,"","syringe");
INSERT INTO Words VALUES (142,220,"","into/enter/insert");
INSERT INTO Words VALUES (142,221,"","money/cash/price");
INSERT INTO Words VALUES (142,222,"","business/trade");
INSERT INTO Words VALUES (142,223,"","safe");
INSERT INTO Words VALUES (142,224,"","bank");
INSERT INTO Words VALUES (142,225,"","notes/paper money");
INSERT INTO Words VALUES (142,226,"","account");
INSERT INTO Words VALUES (142,227,"","safe custody");
INSERT INTO Words VALUES (142,228,"","bankrupt, bankruptcy");
INSERT INTO Words VALUES (142,229,"","disc/pill");
INSERT INTO Words VALUES (142,230,"","to cross out/to blot out/destroy");
INSERT INTO Words VALUES (142,231,"","a ruin");
INSERT INTO Words VALUES (142,232,"","equal/equals/are/same");
INSERT INTO Words VALUES (142,233,"","not equal/different");
INSERT INTO Words VALUES (142,234,"","is proportional to (?)");
INSERT INTO Words VALUES (142,235,"","solid/solid thing");
INSERT INTO Words VALUES (142,236,"","liquid");
INSERT INTO Words VALUES (142,237,"","melting");
INSERT INTO Words VALUES (142,238,"","metal");
INSERT INTO Words VALUES (142,239,"","raw material/material");
INSERT INTO Words VALUES (142,240,"","crystal");
INSERT INTO Words VALUES (142,241,"","classify/classification");
INSERT INTO Words VALUES (142,242,"","crystal axis");
INSERT INTO Words VALUES (142,243,"","change");
INSERT INTO Words VALUES (142,244,"","thing on earth");
INSERT INTO Words VALUES (142,245,"","soap");
INSERT INTO Words VALUES (142,246,"","above/over");
INSERT INTO Words VALUES (142,247,"","below/under");
INSERT INTO Words VALUES (142,248,"","conjunction/junction/joint/union/combination/coalition/alliance/connection/link/couple");
INSERT INTO Words VALUES (142,249,"","tool");
INSERT INTO Words VALUES (142,250,"","connection/junction (basic)");
INSERT INTO Words VALUES (142,251,"","chains");
INSERT INTO Words VALUES (142,252,"","chain link/ring/rings");
INSERT INTO Words VALUES (142,253,"","gas");
INSERT INTO Words VALUES (142,254,"","gas-filled");
INSERT INTO Words VALUES (142,255,"","thermometer");
INSERT INTO Words VALUES (142,256,"","tripod");
INSERT INTO Words VALUES (142,257,"","glass flask/Erlenmeyer");
INSERT INTO Words VALUES (142,258,"","cock/tap");
INSERT INTO Words VALUES (142,259,"","burette");
INSERT INTO Words VALUES (142,260,"","manometer/air pressure");
INSERT INTO Words VALUES (142,261,"","filter process");
INSERT INTO Words VALUES (142,262,"","filtration (laboratory)");
INSERT INTO Words VALUES (142,263,"","calibrated cylinder/measuring glass");
INSERT INTO Words VALUES (142,264,"","solution");
INSERT INTO Words VALUES (142,265,"","solution");
INSERT INTO Words VALUES (142,266,"","The upper part");
INSERT INTO Words VALUES (142,267,"","The middle part");
INSERT INTO Words VALUES (142,268,"","evaluation/the value/human evaluation");
INSERT INTO Words VALUES (142,269,"","to evaluate");
INSERT INTO Words VALUES (142,270,"","precipitation");
INSERT INTO Words VALUES (142,271,"","solution plus sediment");
INSERT INTO Words VALUES (142,272,"","solution plus crystal sediment");
INSERT INTO Words VALUES (142,273,"","diaphragm");
INSERT INTO Words VALUES (142,274,"","filtration (in industry)");
INSERT INTO Words VALUES (142,275,"","osmosis");
INSERT INTO Words VALUES (142,276,"","dialysis (colloid-solution)");
INSERT INTO Words VALUES (142,277,"","of the past");
INSERT INTO Words VALUES (142,278,"","split thing");
INSERT INTO Words VALUES (142,279,"","upper addition/give to");
INSERT INTO Words VALUES (142,280,"","upper subtraction/take from");
INSERT INTO Words VALUES (142,281,"","ionisation");
INSERT INTO Words VALUES (142,282,"","stable (position)");
INSERT INTO Words VALUES (142,283,"","to work/occupation/job");
INSERT INTO Words VALUES (142,284,"","room/compartment/cabin");
INSERT INTO Words VALUES (142,285,"","of the future");
INSERT INTO Words VALUES (142,286,"","quality/value/rational evaluation");
INSERT INTO Words VALUES (142,287,"","ability/to enable");
INSERT INTO Words VALUES (142,288,"","(passive) ability");
INSERT INTO Words VALUES (142,289,"","can/being able");
INSERT INTO Words VALUES (142,290,"","can/being able");
INSERT INTO Words VALUES (142,291,"","nature/creation/safety sign/universe/triangle");
INSERT INTO Words VALUES (142,292,"","intermittent on-going");
INSERT INTO Words VALUES (142,293,"","the structure of nature");
INSERT INTO Words VALUES (142,294,"","man made/make/prepare/produce");
INSERT INTO Words VALUES (142,295,"","supra natural/supra-natural");
INSERT INTO Words VALUES (142,296,"","creator/god");
INSERT INTO Words VALUES (142,297,"","freedom/liberty");
INSERT INTO Words VALUES (142,298,"","behaviour");
INSERT INTO Words VALUES (142,299,"","safe/feeling of protection/feeling of security");
INSERT INTO Words VALUES (142,300,"","rest/calm");
INSERT INTO Words VALUES (142,301,"","enter building");
INSERT INTO Words VALUES (142,302,"","truth");
INSERT INTO Words VALUES (142,303,"","mind/emotion/means");
INSERT INTO Words VALUES (142,304,"","reason/ego/reasoning/rational thought");
INSERT INTO Words VALUES (142,305,"","super ego (conscience)");
INSERT INTO Words VALUES (142,306,"","conscience");
INSERT INTO Words VALUES (142,307,"","human evaluation");
INSERT INTO Words VALUES (142,308,"","doubt");
INSERT INTO Words VALUES (142,309,"","doubt");
INSERT INTO Words VALUES (142,310,"","certainty");
INSERT INTO Words VALUES (142,311,"","no question");
INSERT INTO Words VALUES (142,312,"","classification");
INSERT INTO Words VALUES (142,313,"","interest");
INSERT INTO Words VALUES (142,314,"","strong interest");
INSERT INTO Words VALUES (142,315,"","idea/mind flash");
INSERT INTO Words VALUES (142,316,"","the interest");
INSERT INTO Words VALUES (142,317,"","correct");
INSERT INTO Words VALUES (142,318,"","incorrect");
INSERT INTO Words VALUES (142,319,"","tolerance");
INSERT INTO Words VALUES (142,320,"","moral tolerant");
INSERT INTO Words VALUES (142,321,"","right/good");
INSERT INTO Words VALUES (142,322,"","wrong/bad/immoral");
INSERT INTO Words VALUES (142,323,"","not right");
INSERT INTO Words VALUES (142,324,"","opinion");
INSERT INTO Words VALUES (142,325,"","observation");
INSERT INTO Words VALUES (142,326,"","intent/purpose of mind");
INSERT INTO Words VALUES (142,327,"","proposal");
INSERT INTO Words VALUES (142,328,"","opposition/contradiction/objection");
INSERT INTO Words VALUES (142,329,"","progress");
INSERT INTO Words VALUES (142,330,"","spite/courage");
INSERT INTO Words VALUES (142,331,"","wish/desire/want");
INSERT INTO Words VALUES (142,332,"","drawing the line");
INSERT INTO Words VALUES (142,333,"1","egoistic");
INSERT INTO Words VALUES (142,334,"2","altruistic");
INSERT INTO Words VALUES (142,335,"","hairdresser/hair");
INSERT INTO Words VALUES (142,336,"","second part/to be (part)");
INSERT INTO Words VALUES (142,337,"","use/useful");
INSERT INTO Words VALUES (142,338,"","security");
INSERT INTO Words VALUES (142,339,"","select/elect/vote");
INSERT INTO Words VALUES (142,340,"","will");
INSERT INTO Words VALUES (142,341,"","refusal");
INSERT INTO Words VALUES (142,342,"","permission");
INSERT INTO Words VALUES (142,343,"","allow/permit");
INSERT INTO Words VALUES (142,344,"","decision");
INSERT INTO Words VALUES (142,345,"","experience/past");
INSERT INTO Words VALUES (142,346,"","anticipation/future/prophecy/prediction/forecast");
INSERT INTO Words VALUES (142,347,"","knowledge");
INSERT INTO Words VALUES (142,348,"1","THE (thing)");
INSERT INTO Words VALUES (142,349,"","knowledge");
INSERT INTO Words VALUES (142,350,"","to understand/understanding");
INSERT INTO Words VALUES (142,351,"","closed/enclosed/square/engaged/square");
INSERT INTO Words VALUES (142,352,"","bottom/oven");
INSERT INTO Words VALUES (142,353,"","lid/top/hotplate");
INSERT INTO Words VALUES (142,354,"","thing forwarded");
INSERT INTO Words VALUES (142,355,"","middle/centre/core");
INSERT INTO Words VALUES (142,356,"","left plate");
INSERT INTO Words VALUES (142,357,"","right plate");
INSERT INTO Words VALUES (142,358,"","unit of enclosure");
INSERT INTO Words VALUES (142,359,"","into/to move into/to enter/to insert/to deposit/to input/absorption");
INSERT INTO Words VALUES (142,360,"","to move out/to exit/out of/exhaust/spray/to leave/extract/to output");
INSERT INTO Words VALUES (142,361,"","enclosure with nucleus");
INSERT INTO Words VALUES (142,362,"","in/inside");
INSERT INTO Words VALUES (142,363,"","nucleus");
INSERT INTO Words VALUES (142,364,"","trap");
INSERT INTO Words VALUES (142,365,"","open/vacant");
INSERT INTO Words VALUES (142,366,"","latch");
INSERT INTO Words VALUES (142,367,"","question/INFORMATION/information/problem");
INSERT INTO Words VALUES (142,368,"","separator/conditon point");
INSERT INTO Words VALUES (142,369,"","answer/solution");
INSERT INTO Words VALUES (142,370,"","unconscious/asleep/fainted");
INSERT INTO Words VALUES (142,371,"","subconscious/awake");
INSERT INTO Words VALUES (142,372,"","preconscious");
INSERT INTO Words VALUES (142,373,"","conscious of emotions");
INSERT INTO Words VALUES (142,374,"","conscious of reason");
INSERT INTO Words VALUES (142,375,"","conscious of conscience");
INSERT INTO Words VALUES (142,376,"","beauty");
INSERT INTO Words VALUES (142,377,"","science/philosophy/mind contemplating nature/research");
INSERT INTO Words VALUES (142,378,"","science of mathematics");
INSERT INTO Words VALUES (142,379,"","knowledge of mathematics");
INSERT INTO Words VALUES (142,380,"","calculate");
INSERT INTO Words VALUES (142,381,"","a cardinal number/a cipher/a figure/digital");
INSERT INTO Words VALUES (142,382,"","ordinal number");
INSERT INTO Words VALUES (142,383,"","doubt/truth (in a human's mind)");
INSERT INTO Words VALUES (142,384,"","designing/planning/design/plan/method");
INSERT INTO Words VALUES (142,385,"","benzine-like/hexagonal");
INSERT INTO Words VALUES (142,386,"","upper eye lid");
INSERT INTO Words VALUES (142,387,"","eye brow");
INSERT INTO Words VALUES (142,388,"","to pass through");
INSERT INTO Words VALUES (142,389,"","to partially pass thorugh");
INSERT INTO Words VALUES (142,390,"","awake");
INSERT INTO Words VALUES (142,391,"","asleep/sleep");
INSERT INTO Words VALUES (142,392,"","discoverer/discovery");
INSERT INTO Words VALUES (142,393,"","eye side on");
INSERT INTO Words VALUES (142,394,"","back of eye side on");
INSERT INTO Words VALUES (142,395,"","front of eye side on");
INSERT INTO Words VALUES (142,396,"","outside front of eye side on");
INSERT INTO Words VALUES (142,397,"","mark spot/mark blot");
INSERT INTO Words VALUES (142,398,"","optical");
INSERT INTO Words VALUES (142,399,"","camera");
INSERT INTO Words VALUES (142,400,"","colour");
INSERT INTO Words VALUES (142,401,"","deaf");
INSERT INTO Words VALUES (142,402,"","language");
INSERT INTO Words VALUES (142,403,"","earlobe/ear lobe/lobe/ear lug");
INSERT INTO Words VALUES (142,404,"","tip of the ear/ear tip");
INSERT INTO Words VALUES (142,405,"","hand");
INSERT INTO Words VALUES (142,406,"","sound/noise/disturbance/disturb");
INSERT INTO Words VALUES (142,407,"","bell");
INSERT INTO Words VALUES (142,408,"","news");
INSERT INTO Words VALUES (142,409,"","nose");
INSERT INTO Words VALUES (142,410,"","odour/smell");
INSERT INTO Words VALUES (142,411,"","air");
INSERT INTO Words VALUES (142,412,"","upper lip");
INSERT INTO Words VALUES (142,413,"","upper lip");
INSERT INTO Words VALUES (142,414,"","dumb");
INSERT INTO Words VALUES (142,415,"","to generalise");
INSERT INTO Words VALUES (142,416,"","name/sign/signature/name is");
INSERT INTO Words VALUES (142,417,"","name and address");
INSERT INTO Words VALUES (142,418,"","open speech/public");
INSERT INTO Words VALUES (142,419,"","secret/private");
INSERT INTO Words VALUES (142,420,"","betrayal");
INSERT INTO Words VALUES (142,421,"","(about) food");
INSERT INTO Words VALUES (142,422,"","cheese");
INSERT INTO Words VALUES (142,423,"","bread/cake");
INSERT INTO Words VALUES (142,424,"","(mid) thing/matter");
INSERT INTO Words VALUES (142,425,"","glass/wine glass/glassware/drink glass");
INSERT INTO Words VALUES (142,426,"","throw out");
INSERT INTO Words VALUES (142,427,"","container for throwing into");
INSERT INTO Words VALUES (142,428,"","cigarette");
INSERT INTO Words VALUES (142,429,"","finger pointing");
INSERT INTO Words VALUES (142,430,"","boxing");
INSERT INTO Words VALUES (142,431,"","ground left pointer");
INSERT INTO Words VALUES (142,432,"","tool/instrument");
INSERT INTO Words VALUES (142,433,"","bugle/horn");
INSERT INTO Words VALUES (142,434,"","left hand");
INSERT INTO Words VALUES (142,435,"","arm/left arm");
INSERT INTO Words VALUES (142,436,"","right arm");
INSERT INTO Words VALUES (142,437,"","upper arm");
INSERT INTO Words VALUES (142,438,"","strong arm");
INSERT INTO Words VALUES (142,439,"","to force/to require");
INSERT INTO Words VALUES (142,440,"","legs and feet");
INSERT INTO Words VALUES (142,441,"","leg");
INSERT INTO Words VALUES (142,442,"","foot");
INSERT INTO Words VALUES (142,443,"","ground right pointer");
INSERT INTO Words VALUES (142,444,"","sole");
INSERT INTO Words VALUES (142,445,"","mid-upper metal");
INSERT INTO Words VALUES (142,446,"","head");
INSERT INTO Words VALUES (142,447,"","face");
INSERT INTO Words VALUES (142,448,"","chin");
INSERT INTO Words VALUES (142,449,"","neck");
INSERT INTO Words VALUES (142,450,"","profile");
INSERT INTO Words VALUES (142,451,"","trunk");
INSERT INTO Words VALUES (142,452,"","shoulder");
INSERT INTO Words VALUES (142,453,"","chest");
INSERT INTO Words VALUES (142,454,"","stomach");
INSERT INTO Words VALUES (142,455,"","teeth");
INSERT INTO Words VALUES (142,456,"","to fix (in position)");
INSERT INTO Words VALUES (142,457,"","time/date");
INSERT INTO Words VALUES (142,458,"","watch");
INSERT INTO Words VALUES (142,459,"","degree");
INSERT INTO Words VALUES (142,460,"","minute");
INSERT INTO Words VALUES (142,461,"","second");
INSERT INTO Words VALUES (142,462,"","time interval/time limit/it takes/duration");
INSERT INTO Words VALUES (142,463,"","angle/phase (angular)");
INSERT INTO Words VALUES (142,464,"","right angle");
INSERT INTO Words VALUES (142,465,"","provide the value of");
INSERT INTO Words VALUES (142,466,"","where?");
INSERT INTO Words VALUES (142,467,"","anywhere/wherever");
INSERT INTO Words VALUES (142,468,"","world");
INSERT INTO Words VALUES (142,469,"","lightning");
INSERT INTO Words VALUES (142,470,"","wind");
INSERT INTO Words VALUES (142,471,"","pipe/shaft");
INSERT INTO Words VALUES (142,472,"","ground fog/fog/slippery road");
INSERT INTO Words VALUES (142,473,"","low ceiling");
INSERT INTO Words VALUES (142,474,"","upper addition/add to");
INSERT INTO Words VALUES (142,475,"","ratioed/related to");
INSERT INTO Words VALUES (142,476,"","mountain");
INSERT INTO Words VALUES (142,477,"","base/basis");
INSERT INTO Words VALUES (142,478,"","slope");
INSERT INTO Words VALUES (142,479,"","summit");
INSERT INTO Words VALUES (142,480,"","ridge");
INSERT INTO Words VALUES (142,481,"","strata horizontal");
INSERT INTO Words VALUES (142,482,"","strata oblique");
INSERT INTO Words VALUES (142,483,"","angle");
INSERT INTO Words VALUES (142,484,"","syncline");
INSERT INTO Words VALUES (142,485,"","anticline");
INSERT INTO Words VALUES (142,486,"","mine");
INSERT INTO Words VALUES (142,487,"","mining");
INSERT INTO Words VALUES (142,488,"","mining");
INSERT INTO Words VALUES (142,489,"","stone");
INSERT INTO Words VALUES (142,490,"","ore");
INSERT INTO Words VALUES (142,491,"","pouring pipes");
INSERT INTO Words VALUES (142,492,"","sand/dirt/powder/dust");
INSERT INTO Words VALUES (142,493,"","dust bag");
INSERT INTO Words VALUES (142,494,"","hole");
INSERT INTO Words VALUES (142,495,"","water hole");
INSERT INTO Words VALUES (142,496,"","rain");
INSERT INTO Words VALUES (142,497,"","snow");
INSERT INTO Words VALUES (142,498,"","hail");
INSERT INTO Words VALUES (142,499,"","puddle/water on ground");
INSERT INTO Words VALUES (142,500,"","stream/current");
INSERT INTO Words VALUES (142,501,"","freshly oiled road");
INSERT INTO Words VALUES (142,502,"","water below ground");
INSERT INTO Words VALUES (142,503,"","water flowing downhill");
INSERT INTO Words VALUES (142,504,"","sinking a bore/drilling into the ground");
INSERT INTO Words VALUES (142,505,"","artesian well/spring");
INSERT INTO Words VALUES (142,506,"","deliquescence (water to hygroscopic)");
INSERT INTO Words VALUES (142,507,"","efflorescence");
INSERT INTO Words VALUES (142,508,"","cloud");
INSERT INTO Words VALUES (142,509,"","freezing");
INSERT INTO Words VALUES (142,510,"","ice");
INSERT INTO Words VALUES (142,511,"","thawing/defrosting");
INSERT INTO Words VALUES (142,512,"","weather");
INSERT INTO Words VALUES (142,513,"","umbrella");
INSERT INTO Words VALUES (142,514,"","water tank/hydrant");
INSERT INTO Words VALUES (142,515,"","oil/fat");
INSERT INTO Words VALUES (142,516,"2","another");
INSERT INTO Words VALUES (142,517,"","open fire");
INSERT INTO Words VALUES (142,518,"","stove/furnace/energy");
INSERT INTO Words VALUES (142,519,"","extinguish");
INSERT INTO Words VALUES (142,520,"","cook/cooking/boiling");
INSERT INTO Words VALUES (142,521,"","bake/baking");
INSERT INTO Words VALUES (142,522,"","grill/frying");
INSERT INTO Words VALUES (142,523,"","pen/writing tool/writing stick");
INSERT INTO Words VALUES (142,524,"","fountain pen");
INSERT INTO Words VALUES (142,525,"","pen and ink");
INSERT INTO Words VALUES (142,526,"","ink");
INSERT INTO Words VALUES (142,527,"","line");
INSERT INTO Words VALUES (142,528,"","book/a writing");
INSERT INTO Words VALUES (142,529,"","envelope/letter/correspondence");
INSERT INTO Words VALUES (142,530,"","parcel/package");
INSERT INTO Words VALUES (142,531,"","post card");
INSERT INTO Words VALUES (142,532,"","stamp");
INSERT INTO Words VALUES (142,533,"","cancellation");
INSERT INTO Words VALUES (142,534,"","sword/knife/cutter/cutlery");
INSERT INTO Words VALUES (142,535,"","plough");
INSERT INTO Words VALUES (142,536,"","scissors");
INSERT INTO Words VALUES (142,537,"","defence");
INSERT INTO Words VALUES (142,538,"","war/fight/military");
INSERT INTO Words VALUES (142,539,"","gun/rifle");
INSERT INTO Words VALUES (142,540,"","movement/motion");
INSERT INTO Words VALUES (142,541,"","carry/transport/fetch/get");
INSERT INTO Words VALUES (142,542,"","ratio/division");
INSERT INTO Words VALUES (142,543,"","car/vehicle/motorcar/carriage");
INSERT INTO Words VALUES (142,544,"","railway/rail");
INSERT INTO Words VALUES (142,545,"","tram/train");
INSERT INTO Words VALUES (142,546,"","steam train/steam engine");
INSERT INTO Words VALUES (142,547,"","railway engine (BPB)");
INSERT INTO Words VALUES (142,548,"","motor bus");
INSERT INTO Words VALUES (142,549,"","bus (BPB)");
INSERT INTO Words VALUES (142,550,"","motor car");
INSERT INTO Words VALUES (142,551,"","garage");
INSERT INTO Words VALUES (142,552,"","tow truck/wreck crane");
INSERT INTO Words VALUES (142,553,"","petrol/gasoline");
INSERT INTO Words VALUES (142,554,"","crossing/transverse");
INSERT INTO Words VALUES (142,555,"","across");
INSERT INTO Words VALUES (142,556,"","key");
INSERT INTO Words VALUES (142,557,"","box/suitcase/hand luggage");
INSERT INTO Words VALUES (142,558,"","in the room/in the cabin");
INSERT INTO Words VALUES (142,559,"","bowl/container/vessel/hold");
INSERT INTO Words VALUES (142,560,"","full/complete");
INSERT INTO Words VALUES (142,561,"","well/thorough");
INSERT INTO Words VALUES (142,562,"","overflow/too much");
INSERT INTO Words VALUES (142,563,"","enough/sufficient");
INSERT INTO Words VALUES (142,564,"","almost");
INSERT INTO Words VALUES (142,565,"","contentment/rich/fortunate/satisfied");
INSERT INTO Words VALUES (142,566,"","contentment in life");
INSERT INTO Words VALUES (142,567,"","grip/hold");
INSERT INTO Words VALUES (142,568,"","receive/get/take/pick up/obtain/accept/absorb/acquire/accumulate/collect");
INSERT INTO Words VALUES (142,569,"","give/offer/let go/contribute/present/release/award/dispense/issue");
INSERT INTO Words VALUES (142,570,"","to exchange/to change/interchange/substitute/convert/barter/swap/reciprocate");
INSERT INTO Words VALUES (142,571,"","for/in exchange for/against");
INSERT INTO Words VALUES (142,572,"","goods/merchandise");
INSERT INTO Words VALUES (142,573,"","bath");
INSERT INTO Words VALUES (142,574,"","tender");
INSERT INTO Words VALUES (142,575,"","standing");
INSERT INTO Words VALUES (142,576,"","weak");
INSERT INTO Words VALUES (142,577,"","sit");
INSERT INTO Words VALUES (142,578,"","lean");
INSERT INTO Words VALUES (142,579,"","lying down/lying");
INSERT INTO Words VALUES (142,580,"","buried");
INSERT INTO Words VALUES (142,581,"","sick");
INSERT INTO Words VALUES (142,582,"","stretcher");
INSERT INTO Words VALUES (142,583,"","front");
INSERT INTO Words VALUES (142,584,"","genital");
INSERT INTO Words VALUES (142,585,"","needy/in need of support");
INSERT INTO Words VALUES (142,586,"","to help");
INSERT INTO Words VALUES (142,587,"","to help");
INSERT INTO Words VALUES (142,588,"","necessity/required");
INSERT INTO Words VALUES (142,589,"","thought of necessity");
INSERT INTO Words VALUES (142,590,"","mutual help");
INSERT INTO Words VALUES (142,591,"","animal");
INSERT INTO Words VALUES (142,592,"","animal");
INSERT INTO Words VALUES (142,593,"","domesticated animal");
INSERT INTO Words VALUES (142,594,"","horse");
INSERT INTO Words VALUES (142,595,"","cattle/bovine");
INSERT INTO Words VALUES (142,596,"","pig");
INSERT INTO Words VALUES (142,597,"","dog/house animal");
INSERT INTO Words VALUES (142,598,"","feline/cat (BCI)");
INSERT INTO Words VALUES (142,599,"","cat");
INSERT INTO Words VALUES (142,600,"","animal undermining house");
INSERT INTO Words VALUES (142,601,"","insect");
INSERT INTO Words VALUES (142,602,"","bee");
INSERT INTO Words VALUES (142,603,"","insect undermining house");
INSERT INTO Words VALUES (142,604,"","insect undermining crops");
INSERT INTO Words VALUES (142,605,"","insect undermining trees");
INSERT INTO Words VALUES (142,606,"","insect undermining fabric");
INSERT INTO Words VALUES (142,607,"","snail");
INSERT INTO Words VALUES (142,608,"","butterfly");
INSERT INTO Words VALUES (142,609,"","snake");
INSERT INTO Words VALUES (142,610,"","earthworm/worm");
INSERT INTO Words VALUES (142,611,"","spider");
INSERT INTO Words VALUES (142,612,"","bird");
INSERT INTO Words VALUES (142,613,"","domestic bird");
INSERT INTO Words VALUES (142,614,"","water bird");
INSERT INTO Words VALUES (142,615,"","domestic water bird");
INSERT INTO Words VALUES (142,616,"","fish");
INSERT INTO Words VALUES (142,617,"","bacilli");
INSERT INTO Words VALUES (142,618,"","plant");
INSERT INTO Words VALUES (142,619,"","flower");
INSERT INTO Words VALUES (142,620,"","garden");
INSERT INTO Words VALUES (142,621,"","metaphor/figure of speech/flowery words");
INSERT INTO Words VALUES (142,622,"","poetical metaphor/flowery speech");
INSERT INTO Words VALUES (142,623,"","grown up/adult");
INSERT INTO Words VALUES (142,624,"","grass");
INSERT INTO Words VALUES (142,625,"","meadow");
INSERT INTO Words VALUES (142,626,"","field/crop");
INSERT INTO Words VALUES (142,627,"","farm");
INSERT INTO Words VALUES (142,628,"","vegetables");
INSERT INTO Words VALUES (142,629,"","fruit");
INSERT INTO Words VALUES (142,630,"","berry");
INSERT INTO Words VALUES (142,631,"","vine berry");
INSERT INTO Words VALUES (142,632,"","underground vegetable");
INSERT INTO Words VALUES (142,633,"","vegetable/fruit above ground");
INSERT INTO Words VALUES (142,634,"","roots");
INSERT INTO Words VALUES (142,635,"","mushroom");
INSERT INTO Words VALUES (142,636,"","tree");
INSERT INTO Words VALUES (142,637,"","tree trunk/trunk");
INSERT INTO Words VALUES (142,638,"","shrub");
INSERT INTO Words VALUES (142,639,"","park (BPB)");
INSERT INTO Words VALUES (142,640,"","electricity/live wire");
INSERT INTO Words VALUES (142,641,"","conducting electricity");
INSERT INTO Words VALUES (142,642,"","insulation");
INSERT INTO Words VALUES (142,643,"","atom");
INSERT INTO Words VALUES (142,644,"","positive (charge)");
INSERT INTO Words VALUES (142,645,"","cation");
INSERT INTO Words VALUES (142,646,"","anion");
INSERT INTO Words VALUES (142,647,"","proton");
INSERT INTO Words VALUES (142,648,"","electron");
INSERT INTO Words VALUES (142,649,"","positron");
INSERT INTO Words VALUES (142,650,"","neutron");
INSERT INTO Words VALUES (142,651,"","deuteron");
INSERT INTO Words VALUES (142,652,"","in layers");
INSERT INTO Words VALUES (142,653,"","elements");
INSERT INTO Words VALUES (142,654,"","hydrogen/H");
INSERT INTO Words VALUES (142,655,"","helium/He");
INSERT INTO Words VALUES (142,656,"","lithium/Li");
INSERT INTO Words VALUES (142,657,"","beryllium/Be");
INSERT INTO Words VALUES (142,658,"","boron/B");
INSERT INTO Words VALUES (142,659,"","carbon/C");
INSERT INTO Words VALUES (142,660,"","nitrogen/N");
INSERT INTO Words VALUES (142,661,"","oxygen/O");
INSERT INTO Words VALUES (142,662,"","fluorine/F");
INSERT INTO Words VALUES (142,663,"","aluminium/Al");
INSERT INTO Words VALUES (142,664,"","silicon/Si");
INSERT INTO Words VALUES (142,665,"","phosphorus/P");
INSERT INTO Words VALUES (142,666,"","sulphur/S");
INSERT INTO Words VALUES (142,667,"","argon/Ar");
INSERT INTO Words VALUES (142,668,"","potassium/K");
INSERT INTO Words VALUES (142,669,"","calcium/Ca");
INSERT INTO Words VALUES (142,670,"","titanium/Ti");
INSERT INTO Words VALUES (142,671,"","manganese/Mn");
INSERT INTO Words VALUES (142,672,"","iron/Fe");
INSERT INTO Words VALUES (142,673,"","nickel/Ni");
INSERT INTO Words VALUES (142,674,"","copper/Cu");
INSERT INTO Words VALUES (142,675,"","zinc/Zn");
INSERT INTO Words VALUES (142,676,"","germanium/Ge");
INSERT INTO Words VALUES (142,677,"","arsenic/As");
INSERT INTO Words VALUES (142,678,"","tin/Sn");
INSERT INTO Words VALUES (142,679,"","neodymium/Nd");
INSERT INTO Words VALUES (142,680,"","erbium/Er");
INSERT INTO Words VALUES (142,681,"","ytterbium/Yb");
INSERT INTO Words VALUES (142,682,"","mercury/Hg");
INSERT INTO Words VALUES (142,683,"","lead/Pb");
INSERT INTO Words VALUES (142,684,"","radium/Ra");
INSERT INTO Words VALUES (142,685,"","uranium/U");
INSERT INTO Words VALUES (142,686,"","neptunium/Np");
INSERT INTO Words VALUES (142,687,"","plutonium/Pu");
INSERT INTO Words VALUES (142,688,"","will be absorbed/absorbs");
INSERT INTO Words VALUES (142,689,"","ejects");
INSERT INTO Words VALUES (142,690,"","chemistry/chemical");
INSERT INTO Words VALUES (142,691,"","chemical thing/a chemical/reagent");
INSERT INTO Words VALUES (142,692,"","chemical process");
INSERT INTO Words VALUES (142,693,"","salt");
INSERT INTO Words VALUES (142,694,"","colloid");
INSERT INTO Words VALUES (142,695,"","suspension");
INSERT INTO Words VALUES (142,696,"","sol/colloid in liquid");
INSERT INTO Words VALUES (142,697,"","coagulation");
INSERT INTO Words VALUES (142,698,"","eutectic");
INSERT INTO Words VALUES (142,699,"","physics");
INSERT INTO Words VALUES (142,700,"","physics");
INSERT INTO Words VALUES (142,701,"","mid-upper thing");
INSERT INTO Words VALUES (142,702,"","forward and reverse");
INSERT INTO Words VALUES (142,703,"","mass");
INSERT INTO Words VALUES (142,704,"","gravitation");
INSERT INTO Words VALUES (142,705,"","microscope");
INSERT INTO Words VALUES (142,706,"","property/quality (in science)");
INSERT INTO Words VALUES (142,707,"","compare");
INSERT INTO Words VALUES (142,708,"","diameter");
INSERT INTO Words VALUES (142,709,"","circular area/cross sectional area");
INSERT INTO Words VALUES (142,710,"","structure");
INSERT INTO Words VALUES (142,711,"","parallel/copy/duplicate");
INSERT INTO Words VALUES (142,712,"","vertical/upright");
INSERT INTO Words VALUES (142,713,"","horizontal");
INSERT INTO Words VALUES (142,714,"","rectangle");
INSERT INTO Words VALUES (142,715,"","parallelogram");
INSERT INTO Words VALUES (142,716,"","crystal axis");
INSERT INTO Words VALUES (142,717,"","tesseral (axis perspective)");
INSERT INTO Words VALUES (142,718,"","rhombic");
INSERT INTO Words VALUES (142,719,"","cube/box/container/case/tesseral");
INSERT INTO Words VALUES (142,720,"","quadrangular prism");
INSERT INTO Words VALUES (142,721,"","pyramid");
INSERT INTO Words VALUES (142,722,"","cylinder/drum");
INSERT INTO Words VALUES (142,723,"","cone");
INSERT INTO Words VALUES (142,724,"","tin/cylinder");
INSERT INTO Words VALUES (142,725,"","bag/sack");
INSERT INTO Words VALUES (142,726,"","bottle");
INSERT INTO Words VALUES (142,727,"","liquid for consumption");
INSERT INTO Words VALUES (142,728,"","graph/plot");
INSERT INTO Words VALUES (142,729,"","plane");
INSERT INTO Words VALUES (142,730,"","plane");
INSERT INTO Words VALUES (142,731,"","space");
INSERT INTO Words VALUES (142,732,"","big/tall/large/bulk");
INSERT INTO Words VALUES (142,733,"","small");
INSERT INTO Words VALUES (142,734,"","short");
INSERT INTO Words VALUES (142,735,"","the height/amplitude");
INSERT INTO Words VALUES (142,736,"","low");
INSERT INTO Words VALUES (142,737,"","far");
INSERT INTO Words VALUES (142,738,"","near/about");
INSERT INTO Words VALUES (142,739,"","as/like/similar/near equal/equivalent to/approximately");
INSERT INTO Words VALUES (142,740,"","deep");
INSERT INTO Words VALUES (142,741,"","shallow");
INSERT INTO Words VALUES (142,742,"","wide/broad");
INSERT INTO Words VALUES (142,743,"","narrow");
INSERT INTO Words VALUES (142,744,"","together");
INSERT INTO Words VALUES (142,745,"","between/within");
INSERT INTO Words VALUES (142,746,"","in");
INSERT INTO Words VALUES (142,747,"","out/outside");
INSERT INTO Words VALUES (142,748,"","broken line");
INSERT INTO Words VALUES (142,749,"","table/platform/stage");
INSERT INTO Words VALUES (142,750,"","table top/tabletop");
INSERT INTO Words VALUES (142,751,"","board-plate");
INSERT INTO Words VALUES (142,752,"","edge");
INSERT INTO Words VALUES (142,753,"","leg end");
INSERT INTO Words VALUES (142,754,"","joist");
INSERT INTO Words VALUES (142,755,"","chair/seat");
INSERT INTO Words VALUES (142,756,"","couch/lounge/easy chair");
INSERT INTO Words VALUES (142,757,"","sofa");
INSERT INTO Words VALUES (142,758,"","bed");
INSERT INTO Words VALUES (142,759,"","mattress");
INSERT INTO Words VALUES (142,760,"","headrest/headboard");
INSERT INTO Words VALUES (142,761,"","pillow end");
INSERT INTO Words VALUES (142,762,"","chest of drawers");
INSERT INTO Words VALUES (142,763,"","wardrobe");
INSERT INTO Words VALUES (142,764,"","shelf");
INSERT INTO Words VALUES (142,765,"","window");
INSERT INTO Words VALUES (142,766,"","outside of the window");
INSERT INTO Words VALUES (142,767,"","punishment/prison window/imprisonment");
INSERT INTO Words VALUES (142,768,"","captive/prisoner (of any kind)");
INSERT INTO Words VALUES (142,769,"","escape");
INSERT INTO Words VALUES (142,770,"","fabric");
INSERT INTO Words VALUES (142,771,"","clothes/dress/attire");
INSERT INTO Words VALUES (142,772,"","against");
INSERT INTO Words VALUES (142,773,"","shirt/life vest");
INSERT INTO Words VALUES (142,774,"","hat");
INSERT INTO Words VALUES (142,775,"","block of/length of something");
INSERT INTO Words VALUES (142,776,"","scales/balance/weight");
INSERT INTO Words VALUES (142,777,"","weight (simplified)");
INSERT INTO Words VALUES (142,778,"","to judge/verdict");
INSERT INTO Words VALUES (142,779,"","fulcrum");
INSERT INTO Words VALUES (142,780,"","friction");
INSERT INTO Words VALUES (142,781,"","sheave (on a pulley)");
INSERT INTO Words VALUES (142,782,"","amplifier (electrical symbol)");
INSERT INTO Words VALUES (142,783,"","buoyancy");
INSERT INTO Words VALUES (142,784,"","tubed liquid");
INSERT INTO Words VALUES (142,785,"","siphon");
INSERT INTO Words VALUES (142,786,"","piston");
INSERT INTO Words VALUES (142,787,"","engineering tolerance/tolerance");
INSERT INTO Words VALUES (142,788,"","compass");
INSERT INTO Words VALUES (142,789,"","geometry");
INSERT INTO Words VALUES (142,790,"","rounded end");
INSERT INTO Words VALUES (142,791,"","triangle");
INSERT INTO Words VALUES (142,792,"","circular/dial");
INSERT INTO Words VALUES (142,793,"","ring/rings");
INSERT INTO Words VALUES (142,794,"","inner ring");
INSERT INTO Words VALUES (142,795,"","pipe");
INSERT INTO Words VALUES (142,796,"","hammer");
INSERT INTO Words VALUES (142,797,"","pliers/pair of pliers");
INSERT INTO Words VALUES (142,798,"","screw");
INSERT INTO Words VALUES (142,799,"","nail");
INSERT INTO Words VALUES (142,800,"","pin");
INSERT INTO Words VALUES (142,801,"","needle");
INSERT INTO Words VALUES (142,802,"","comb");
INSERT INTO Words VALUES (142,803,"","comb (with handle)");
INSERT INTO Words VALUES (142,804,"","brush");
INSERT INTO Words VALUES (142,805,"","brush (vertical handle)");
INSERT INTO Words VALUES (142,806,"","brush (with side handle)");
INSERT INTO Words VALUES (142,807,"","saw");
INSERT INTO Words VALUES (142,808,"","iron/press");
INSERT INTO Words VALUES (142,809,"","spoon");
INSERT INTO Words VALUES (142,810,"","fork");
INSERT INTO Words VALUES (142,811,"","small pot/beaker/small container");
INSERT INTO Words VALUES (142,812,"","pot/handled pot");
INSERT INTO Words VALUES (142,813,"","handled pot/pot with handles");
INSERT INTO Words VALUES (142,814,"","pot with water");
INSERT INTO Words VALUES (142,815,"","vessel with water/pot with water");
INSERT INTO Words VALUES (142,816,"","pot with liquid/vessel with liquid");
INSERT INTO Words VALUES (142,817,"","large pan/pan");
INSERT INTO Words VALUES (142,818,"","small pan");
INSERT INTO Words VALUES (142,819,"","lid");
INSERT INTO Words VALUES (142,820,"","teapot");
INSERT INTO Words VALUES (142,821,"","crockery/plate/dish");
INSERT INTO Words VALUES (142,822,"","soup");
INSERT INTO Words VALUES (142,823,"","hook/hanger");
INSERT INTO Words VALUES (142,824,"","right corner");
INSERT INTO Words VALUES (142,825,"","left corner");
INSERT INTO Words VALUES (142,826,"","right");
INSERT INTO Words VALUES (142,827,"","left");
INSERT INTO Words VALUES (142,828,"","seed/seeds");
INSERT INTO Words VALUES (142,829,"","steamer/boat/ship/vessel");
INSERT INTO Words VALUES (142,830,"","sailing ship");
INSERT INTO Words VALUES (142,831,"","ship wreck");
INSERT INTO Words VALUES (142,832,"","life boat/row boat/rowing boat");
INSERT INTO Words VALUES (142,833,"","float");
INSERT INTO Words VALUES (142,834,"","sail");
INSERT INTO Words VALUES (142,835,"","pennant");
INSERT INTO Words VALUES (142,836,"","fore-deck/forecastle");
INSERT INTO Words VALUES (142,837,"","after-deck/quarter-deck");
INSERT INTO Words VALUES (142,838,"","midships");
INSERT INTO Words VALUES (142,839,"","bottom");
INSERT INTO Words VALUES (142,840,"","keel");
INSERT INTO Words VALUES (142,841,"","funnel");
INSERT INTO Words VALUES (142,842,"","below deck/inside ship");
INSERT INTO Words VALUES (142,843,"","embarkation");
INSERT INTO Words VALUES (142,844,"","disembarkation");
INSERT INTO Words VALUES (142,845,"","harbour");
INSERT INTO Words VALUES (142,846,"","dock");
INSERT INTO Words VALUES (142,847,"","water below");
INSERT INTO Words VALUES (142,848,"","deck (inner)");
INSERT INTO Words VALUES (142,849,"","steering wheel");
INSERT INTO Words VALUES (142,850,"","steering room");
INSERT INTO Words VALUES (142,851,"","boiler");
INSERT INTO Words VALUES (142,852,"","stairs");
INSERT INTO Words VALUES (142,853,"","stairs");
INSERT INTO Words VALUES (142,854,"","double bend");
INSERT INTO Words VALUES (142,855,"","toll bar/customs");
INSERT INTO Words VALUES (142,856,"","road bridge");
INSERT INTO Words VALUES (142,857,"","road under repair");
INSERT INTO Words VALUES (142,858,"","bridge");
INSERT INTO Words VALUES (142,859,"","France/French");
INSERT INTO Words VALUES (142,860,"","door");
INSERT INTO Words VALUES (142,861,"","entrance/IN/reception");
INSERT INTO Words VALUES (142,862,"","exit/OUT");
INSERT INTO Words VALUES (142,863,"","curtain");
INSERT INTO Words VALUES (142,864,"","ceiling");
INSERT INTO Words VALUES (142,865,"","ceiling covering/ceiling");
INSERT INTO Words VALUES (142,866,"","wall covering/wallpaper");
INSERT INTO Words VALUES (142,867,"","floor");
INSERT INTO Words VALUES (142,868,"","floor covering");
INSERT INTO Words VALUES (142,869,"","room open to street/shop front");
INSERT INTO Words VALUES (142,870,"","bath room/bathroom");
INSERT INTO Words VALUES (142,871,"","shower/shower room");
INSERT INTO Words VALUES (142,872,"","machine/motor");
INSERT INTO Words VALUES (142,873,"","wings/to fly/air");
INSERT INTO Words VALUES (142,874,"","wing");
INSERT INTO Words VALUES (142,875,"","air-plane/aeroplane/plane");
INSERT INTO Words VALUES (142,876,"","plane crash");
INSERT INTO Words VALUES (142,877,"","curved thing/bow");
INSERT INTO Words VALUES (142,878,"","around/about");
INSERT INTO Words VALUES (142,879,"","jump");
INSERT INTO Words VALUES (142,880,"","swing");
INSERT INTO Words VALUES (142,881,"","overtake");
INSERT INTO Words VALUES (142,882,"","mixing/mix");
INSERT INTO Words VALUES (142,883,"","circling/circulate");
INSERT INTO Words VALUES (142,884,"","resistor");
INSERT INTO Words VALUES (142,885,"","potentiometer");
INSERT INTO Words VALUES (142,886,"","capacitor");
INSERT INTO Words VALUES (142,887,"","shielded capacitor");
INSERT INTO Words VALUES (142,888,"","varcap");
INSERT INTO Words VALUES (142,889,"","electric cell");
INSERT INTO Words VALUES (142,890,"","electric cell");
INSERT INTO Words VALUES (142,891,"","battery");
INSERT INTO Words VALUES (142,892,"","enter container");
INSERT INTO Words VALUES (142,893,"","electrolysis");
INSERT INTO Words VALUES (142,894,"","anode");
INSERT INTO Words VALUES (142,895,"","cathode");
INSERT INTO Words VALUES (142,896,"","metal bath");
INSERT INTO Words VALUES (142,897,"","alternator/AC motor");
INSERT INTO Words VALUES (142,898,"","generator/DC motor");
INSERT INTO Words VALUES (142,899,"","switch");
INSERT INTO Words VALUES (142,900,"","double throw switch");
INSERT INTO Words VALUES (142,901,"a","ampere-meter");
INSERT INTO Words VALUES (142,902,"V","Voltmeter");
INSERT INTO Words VALUES (142,903,"VA","multimeter");
INSERT INTO Words VALUES (142,904,"f","frequency meter");
INSERT INTO Words VALUES (142,905,"","ear phones/head phones");
INSERT INTO Words VALUES (142,906,"","button (electric)");
INSERT INTO Words VALUES (142,907,"Fe","magnetic waves");
INSERT INTO Words VALUES (142,908,"","line end");
INSERT INTO Words VALUES (142,909,"F","line of field of magnetic force/fields");
INSERT INTO Words VALUES (142,910,"","line of field of electric force/electric field/field");
INSERT INTO Words VALUES (142,911,"","electroscope");
INSERT INTO Words VALUES (142,912,"","multiplexer (electronic)");
INSERT INTO Words VALUES (142,913,"","demultiplexer (electronic)");
INSERT INTO Words VALUES (142,914,"","lens/magnifier");
INSERT INTO Words VALUES (142,915,"","plain concave lens");
INSERT INTO Words VALUES (142,916,"","parabolic reflector");
INSERT INTO Words VALUES (142,917,"","mirror/mirror plane");
INSERT INTO Words VALUES (142,918,"","refraction");
INSERT INTO Words VALUES (142,919,"","divided up/chopped up");
INSERT INTO Words VALUES (142,920,"","prism");
INSERT INTO Words VALUES (142,921,"","ray/light leaving");
INSERT INTO Words VALUES (142,922,"","beam");
INSERT INTO Words VALUES (142,923,"","mode/ray path");
INSERT INTO Words VALUES (142,924,"","clawed bird");
INSERT INTO Words VALUES (142,925,"","swan");
INSERT INTO Words VALUES (142,926,"","penned thing");
INSERT INTO Words VALUES (142,927,"","fan");
INSERT INTO Words VALUES (142,928,"","head with hair");
INSERT INTO Words VALUES (142,929,"","beard (GS)");
INSERT INTO Words VALUES (142,930,"","fact");
INSERT INTO Words VALUES (142,931,"","computer disk/disc (BCI)");
INSERT INTO Words VALUES (142,932,"","contents out");
INSERT INTO Words VALUES (142,933,"","Fire-like thinking");
INSERT INTO Words VALUES (142,934,"","put into mind/increase mind");
--INSERT INTO Words VALUES (142,935,"","");
--INSERT INTO Words VALUES (142,936,"","");
--INSERT INTO Words VALUES (142,937,"","");
--INSERT INTO Words VALUES (142,938,"","");
--INSERT INTO Words VALUES (142,939,"","");
--INSERT INTO Words VALUES (142,940,"","");
--INSERT INTO Words VALUES (142,941,"","");
--INSERT INTO Words VALUES (142,942,"","");
--INSERT INTO Words VALUES (142,943,"","");
--INSERT INTO Words VALUES (142,944,"","");
--INSERT INTO Words VALUES (142,945,"","");
--INSERT INTO Words VALUES (142,946,"","");
--INSERT INTO Words VALUES (142,947,"","");
--INSERT INTO Words VALUES (142,948,"","");
--INSERT INTO Words VALUES (142,949,"","");
--INSERT INTO Words VALUES (142,950,"","");
--INSERT INTO Words VALUES (142,951,"","");
--INSERT INTO Words VALUES (142,952,"","");
--INSERT INTO Words VALUES (142,953,"","");
--INSERT INTO Words VALUES (142,954,"","");
--INSERT INTO Words VALUES (142,955,"","");
--INSERT INTO Words VALUES (142,956,"","");
--INSERT INTO Words VALUES (142,957,"","");
--INSERT INTO Words VALUES (142,958,"","");
--INSERT INTO Words VALUES (142,959,"","");
--INSERT INTO Words VALUES (142,960,"","");
--INSERT INTO Words VALUES (142,961,"","");
--INSERT INTO Words VALUES (142,962,"","");
--INSERT INTO Words VALUES (142,963,"","");
--INSERT INTO Words VALUES (142,964,"","");
--INSERT INTO Words VALUES (142,965,"","");
--INSERT INTO Words VALUES (142,966,"","");
--INSERT INTO Words VALUES (142,967,"","");
--INSERT INTO Words VALUES (142,968,"","");
--INSERT INTO Words VALUES (142,969,"","");
--INSERT INTO Words VALUES (142,970,"","");
--INSERT INTO Words VALUES (142,971,"","");
--INSERT INTO Words VALUES (142,972,"","");
--INSERT INTO Words VALUES (142,973,"","");
--INSERT INTO Words VALUES (142,974,"","");
--INSERT INTO Words VALUES (142,975,"","");
--INSERT INTO Words VALUES (142,976,"","");
--INSERT INTO Words VALUES (142,977,"","");
--INSERT INTO Words VALUES (142,978,"","");
--INSERT INTO Words VALUES (142,979,"","");
--INSERT INTO Words VALUES (142,980,"","");
--INSERT INTO Words VALUES (142,981,"","");
--INSERT INTO Words VALUES (142,982,"","");
--INSERT INTO Words VALUES (142,983,"","");
--INSERT INTO Words VALUES (142,984,"","");
--INSERT INTO Words VALUES (142,985,"","");
--INSERT INTO Words VALUES (142,986,"","");
--INSERT INTO Words VALUES (142,987,"","");
--INSERT INTO Words VALUES (142,988,"","");
--INSERT INTO Words VALUES (142,989,"","");
--INSERT INTO Words VALUES (142,990,"","");
--INSERT INTO Words VALUES (142,991,"","");
--INSERT INTO Words VALUES (142,992,"","");
--INSERT INTO Words VALUES (142,993,"","");
--INSERT INTO Words VALUES (142,994,"","");
--INSERT INTO Words VALUES (142,995,"","");
--INSERT INTO Words VALUES (142,996,"","");
--INSERT INTO Words VALUES (142,997,"","");
--INSERT INTO Words VALUES (142,998,"","");
--INSERT INTO Words VALUES (142,999,"","");
--INSERT INTO Words VALUES (142,1000,"","");
